Lesson 1
kapchegashev/UE4_learning pull request #2
Opened 2020-10-07 09:31 UTC by kapchegashev

1. create project
2. lesson 1 done

2020-10-08 04:56 UTC, SergChernykh commented
Необходимо исправить наименования ассетов в соответствии с code-style 

- [ ] Banana_Blueprint
- [ ] Banana_Material
- [ ] Banana_Model
- [ ] Banana_Texture

2020-10-08 05:01 UTC, SergChernykh requested changes
Необходимо исправить наименования ассетов в соответствии с code-style 

- [x] Banana_Blueprint
- [ ] Banana_Material
- [ ] Banana_Model
- [ ] Banana_Texture

2020-10-08 05:14 UTC, lazgen reviewed
- [ ] Расположить на сцене Player Start таким образом, что бы при запуске камера смотрела сразу на банан

2020-10-08 05:14 UTC, lazgen commented on BananaTurntable.uproject
> +	"Description": ""
Можно добавить какое-нибудь простенькое описание для проекта
и категорию education

2020-10-09 11:41 UTC, kapchegashev commented on BananaTurntable.uproject
> +	"Description": ""
Готово тимлид!

2020-10-09 11:47 UTC, merged