Lesson 2 - done
kapchegashev/UE4_learning pull request #3
Opened 2020-10-14 08:55 UTC by kapchegashev

Lesson 2 - done

2020-10-15 07:46 UTC, SergChernykh commented
- [ ] GM_Tutorial является Bluprint классом, следовательно префикс должен быть BP_

2020-10-15 07:47 UTC, SergChernykh commented
- [ ] Вернуть .gitignore

2020-10-15 07:48 UTC, SergChernykh commented
- [ ] M_Turntable материал нигде не используется, можно удалить.

2020-10-15 07:59 UTC, lazgen commented
Удалить файлы из папок:
- [ ] Intermediate
- [ ] Saved

2020-10-15 08:01 UTC, lazgen commented
Восстановить файлы прошлого урока:
- [ ] BananaTurntable.uproject
- [ ] Content/Banana.umap
- [ ] Content/Banana_BuiltData.uasset
- [ ] Content/BP_Banana.uasset
- [ ] Content/M_Banana.uasset
- [ ] Content/SM_Banana.uasset
- [ ] README.md

2020-10-15 08:05 UTC, SergChernykh requested changes
Поправить то, что указано выше в комментариях.

2020-10-15 10:41 UTC, kapchegashev commented
> * [ ]  M_Turntable материал нигде не используется, можно удалить.
а я хз, может в будущих уроках будет использоваться, не?

2020-10-23 04:56 UTC, kapchegashev commented
All done

2020-10-23 04:58 UTC, merged